Update populate_aartis.yml

diff --git a/.github/workflows/populate_aartis.yml b/.github/workflows/populate_aartis.yml
--- a/.github/workflows/populate_aartis.yml
+++ b/.github/workflows/populate_aartis.yml
@@ -18,7 +18,15 @@ jobs:
       - name: Install Dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install -r backend/requirements.txt
+          if [ -f "requirements.txt" ]; then
+            pip install -r requirements.txt
+          elif [ -f "backend/requirements.txt" ]; then
+            pip install -r backend/requirements.txt
+          else
+            echo "requirements.txt not found!"
+            ls -R
+            exit 1
+          fi
 
       - name: Install FFmpeg
         run: sudo apt-get install -y ffmpeg
@@ -31,7 +39,6 @@ jobs:
           CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
           CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
           CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
-          PYTHONPATH: backend
+          PYTHONPATH: .
         run: |
-          cd backend
           python scripts/populate_aartis.py
